### ISSUE TITLE
JIRA to Notion for Windows

### ISSUE THREAD

**Issue by cihanbozkurt** [keremkoseoglu/Jira2Notion#4]
Hi Kerem,

Is it possible to create this little program for Windows? i would love to use this useful program in my Windows 10 environment. And i am pretty sure that there are lots of W10 users looking for this kind of tool for their Notion :)

Thank you in advance.

**Comment by keremkoseoglu** [comment]
Thanks for reminding me, @cihanbozkurt :) I have labeled this as an enhancement request, I will get to it when I can.

**Comment by keremkoseoglu** [comment]
@cihanbozkurt hi :) I have extended the program so that it is usable from non-MacOS machines as well. I have also extended the readme file and included very detailed instructions for installation & setup - check the main page of the project.

When you start the program on Windows, you will get a popup asking for your issue number. You have to type your issue number manually; example: VOL-12345 . 

I don't have a solution to read the issue number from your Windows browser automatically at this time. MacOS has a technology called "AppleScript", which can act like an RPA to fetch info from applications. I suspect that it can be done on Windows with PowerShell, but I'm not sure. You are more than welcome to fork this project, add PowerShell functionality and send a pull request.
